### ISSUE TITLE
Effects panels needs styling

### ISSUE THREAD

**Issue by PrototypeESBU** [ronijaakkola/foundryvtt-lights-out-theme-shadowdark#2]
Currently the effects panels stacks on top of where the tool bar is now:
![image](https://github.com/user-attachments/assets/fa32e07a-e415-4dbb-a0f0-cea82dc49577)

**Comment by ronijaakkola** [comment]
Thanks for reporting! I will check this out when I have time.

**Comment by ronijaakkola** [comment]
Fixed in [v1.04](https://github.com/ronijaakkola/foundryvtt-lights-out-theme-shadowdark/releases/tag/v1.04).
