### ISSUE TITLE
Roll Table "Add Row" Icon is absent when theme is active

### ISSUE THREAD

**Issue by git-steve-git** [ronijaakkola/foundryvtt-lights-out-theme-shadowdark#4]
I noticed an odd issue tonight: If I have this theme module active, when editing a roll table, the plus icon (+) to add a new row to the table is missing.  As are the icons that go alongside each row, although that's less of a concern to me, personally =P

I've confirmed the issue appears when this theme is the only module active in the world, and it goes away when no modules are active.

![missing-plus-icon](https://github.com/user-attachments/assets/b1b243fa-d0db-44ff-a85e-f2e7dec91363)

**Comment by ronijaakkola** [comment]
Thanks for reporting this! Some style override probably also hits something else I was not aware of. I will take a look at this when I have time.

**Comment by ronijaakkola** [comment]
Fixed in [version 1.03](https://github.com/ronijaakkola/foundryvtt-lights-out-theme-shadowdark/releases/tag/v1.03).
