### ISSUE TITLE
In some cases, sidebar tabs overflow the visual

### ISSUE THREAD

**Issue by ronijaakkola** [ronijaakkola/foundryvtt-lights-out-theme-shadowdark#5]
Reported in The Arcane Library Discord.

Foundry V11 315, Shadowdark 3.0.0

![image](https://github.com/user-attachments/assets/b7a2ef18-2d96-4bd2-a4c6-5bb6335042a0)

![image](https://github.com/user-attachments/assets/fc6badd1-7694-4d48-9768-ce76bf5e69bb)

**Comment by Mad7eo** [comment]
solved with the latest update
