### ISSUE TITLE
Active Player Menu is hidden with no way to reshow

### ISSUE THREAD

**Issue by juggernaut1337** [ronijaakkola/foundryvtt-lights-out-theme-shadowdark#9]
The player menu is the only way for players to set their active character in a game where they control more than one. This menu is hidden by the Lights Out theme and cannot be re-enabled. Please add a check box in the settings to show it again.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a new setting to control player menu visibility and modified the main script to respect this setting. This allows players to access the menu for setting their active character when controlling multiple characters.

You can review changes in this commit: https://github.com/mnmnk43434/ronijaakkola-foundryvtt-lights-out-theme-shadowdark-9/commit/7e7a65f1e6259e9baed16b8d4f09c4185cee4a7e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ronijaakkola** [comment]
Fix made by @PrototypeESBU released in version [1.06](https://github.com/ronijaakkola/foundryvtt-lights-out-theme-shadowdark/releases/tag/v1.06). You can now make the Player List visible either for the GM or both GM and players.
